# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jiagou.io
email: aaron.cheung@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a great place to talk about Architecture in Chinese.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiagou.io" # the base hostname & protocol for your site
twitter_username: aaronz
github_username:  aaronz

# Build settings
markdown: kramdown
